/**
 * Client-side search over a prebuilt structural index.
 *
 * The index (`public/search-index.json`, generated by `scripts/sync.ts`) holds
 * only concept names, document titles, headings, Q&A questions and exercise
 * names — no article bodies. That keeps it ~600 KB raw / ~100 KB brotli, small
 * enough to ship once and query entirely in the browser: zero database round
 * trips per keystroke, which matters because the database sits in us-east-2
 * while the reader does not.
 */

export const SEARCH_INDEX_URL = '/search-index.json';

/** Below this, the dropdown shows a hint instead of results. */
export const MIN_QUERY_LENGTH = 2;

/** Tokens this short must hit a word boundary — see `tokenScore`. */
const SHORT_TOKEN_LENGTH = 2;

export const INDEX_VERSION = 1;

export type RowKind =
  | 'c' // concept from knowledge/GLOBAL_INDEX.md, pointing at its owner doc
  | 'd' // theory document title
  | 'h' // heading H2–H4 inside a theory document
  | 'q' // interview question
  | 'x'; // exercise

export interface IndexRow {
  k: RowKind;
  /** Index into `SearchIndex.mods` — cheaper than repeating the slug 6.5k times. */
  m: number;
  /** Display text. */
  t: string;
  /** Theory doc slug ('c' | 'd' | 'h') or exercise slug ('x'). */
  s?: string;
  /** Heading anchor id ('h'), matching what `lib/markdown.tsx` renders. */
  a?: string;
  /** Heading level 2–4 ('h'). */
  l?: number;
  /** Q&A question number ('q'). */
  n?: number;
  /** 1 when this row is also a canonical concept in GLOBAL_INDEX.md. */
  c?: 1;
}

export interface IndexModule {
  slug: string;
  title: string;
}

export interface SearchIndex {
  v: number;
  generatedAt: string;
  mods: IndexModule[];
  rows: IndexRow[];
}

/** Index plus the derived lookups that would otherwise be rebuilt per keystroke. */
export interface PreparedIndex {
  mods: IndexModule[];
  rows: IndexRow[];
  /** `normalize(row.t)`, precomputed once at load. */
  norm: string[];
  /** `${moduleIndex}/${docSlug}` → document title, for result breadcrumbs. */
  docTitles: Map<string, string>;
}

export type ResultGroup = 'concept' | 'theory' | 'qa' | 'exercise';

export interface SearchResult {
  row: IndexRow;
  group: ResultGroup;
  score: number;
  href: string;
  /** Module title plus, for headings, the document they live in. */
  breadcrumb: string;
  /** Matched spans over `row.t`, for <mark> highlighting. */
  ranges: [number, number][];
}

/**
 * Deliberately length-preserving: lowercasing and ё→е are 1:1 for Latin and
 * Cyrillic, so match offsets computed here map straight back onto the original
 * text for highlighting. Do not add NFD stripping or whitespace collapsing.
 */
export function normalize(s: string): string {
  return s.toLowerCase().replace(/ё/g, 'е');
}

export function prepareIndex(index: SearchIndex): PreparedIndex {
  const norm = index.rows.map((r) => normalize(r.t));
  const docTitles = new Map<string, string>();
  for (const r of index.rows) {
    if (r.k === 'd' && r.s) docTitles.set(`${r.m}/${r.s}`, r.t);
  }
  return { mods: index.mods, rows: index.rows, norm, docTitles };
}

export function tokenize(query: string): string[] {
  return normalize(query).split(/\s+/).filter(Boolean);
}

function isWordChar(ch: string): boolean {
  return /[\p{L}\p{N}]/u.test(ch);
}

/**
 * Where `tok` sits on a word boundary inside `hay`: as a whole word, or merely
 * as the start of a longer one. The distinction matters — searching `cas`
 * should put "CAS (Compare-And-Swap)" above "cascade types".
 */
function wordBoundaryHit(hay: string, tok: string): { whole: number; prefix: number } {
  let prefix = -1;
  let from = 0;
  for (;;) {
    const i = hay.indexOf(tok, from);
    if (i === -1) break;
    if (i === 0 || !isWordChar(hay[i - 1])) {
      const after = i + tok.length;
      if (after >= hay.length || !isWordChar(hay[after])) return { whole: i, prefix };
      if (prefix === -1) prefix = i;
    }
    from = i + 1;
  }
  return { whole: -1, prefix };
}

/**
 * Score one token against one candidate, and report where it matched. The
 * tiers, high to low: the whole string, a whole word, the start of the string,
 * the start of a word, anywhere at all.
 *
 * A token of 2 characters must land on a word boundary. That is what makes a
 * 2-character minimum usable: `gc`, `vt`, `n+1` find their terms, while `gc`
 * buried inside an unrelated word does not surface.
 */
function tokenScore(hay: string, tok: string): { score: number; at: number } {
  if (hay === tok) return { score: 100, at: 0 };

  const { whole, prefix } = wordBoundaryHit(hay, tok);
  if (whole !== -1) return { score: whole === 0 ? 75 : 70, at: whole };
  if (hay.startsWith(tok)) return { score: 60, at: 0 };
  if (prefix !== -1) return { score: 40, at: prefix };

  if (tok.length <= SHORT_TOKEN_LENGTH) return { score: -1, at: -1 };

  const anywhere = hay.indexOf(tok);
  return anywhere === -1 ? { score: -1, at: -1 } : { score: 15, at: anywhere };
}

const KIND_BONUS: Record<RowKind, number> = { c: 30, d: 25, q: 12, x: 8, h: 0 };
const LEVEL_BONUS: Record<number, number> = { 2: 18, 3: 10, 4: 6 };
const CONCEPT_BONUS = KIND_BONUS.c;
const CURRENT_MODULE_BONUS = 8;

function kindBonus(row: IndexRow): number {
  const base = row.k === 'h' ? (LEVEL_BONUS[row.l ?? 3] ?? 6) : KIND_BONUS[row.k];
  return row.c === 1 ? Math.max(base, CONCEPT_BONUS) : base;
}

export function groupOf(row: IndexRow): ResultGroup {
  if (row.k === 'q') return 'qa';
  if (row.k === 'x') return 'exercise';
  if (row.k === 'c' || row.c === 1) return 'concept';
  return 'theory';
}

export function hrefFor(row: IndexRow, mods: IndexModule[]): string {
  const slug = mods[row.m]?.slug ?? '';
  switch (row.k) {
    case 'q':
      return `/modules/${slug}/qa#qa-${row.n}`;
    case 'x':
      return `/modules/${slug}/exercises/${row.s}`;
    case 'h':
      return `/modules/${slug}/theory/${row.s}#${row.a}`;
    default:
      return `/modules/${slug}/theory/${row.s}`;
  }
}

/** Merge overlapping/adjacent spans so highlighting emits one <mark> each. */
function mergeRanges(ranges: [number, number][]): [number, number][] {
  if (ranges.length < 2) return ranges;
  const sorted = [...ranges].sort((a, b) => a[0] - b[0]);
  const out: [number, number][] = [sorted[0]];
  for (const [start, end] of sorted.slice(1)) {
    const last = out[out.length - 1];
    if (start <= last[1]) last[1] = Math.max(last[1], end);
    else out.push([start, end]);
  }
  return out;
}

export const MAX_RESULTS = 30;

/**
 * All tokens must match (AND). Results are ranked by match quality plus a bonus
 * for the kind of entry, with shorter titles winning ties — a heading that is
 * exactly the term beats a long one that merely contains it.
 */
export function search(
  index: PreparedIndex,
  query: string,
  currentModuleSlug?: string,
  limit = MAX_RESULTS,
): SearchResult[] {
  const tokens = tokenize(query);
  if (tokens.length === 0 || query.trim().length < MIN_QUERY_LENGTH) return [];

  const currentModule = currentModuleSlug
    ? index.mods.findIndex((m) => m.slug === currentModuleSlug)
    : -1;

  const hits: SearchResult[] = [];

  for (let i = 0; i < index.rows.length; i++) {
    const hay = index.norm[i];
    let score = 0;
    const ranges: [number, number][] = [];

    let matched = true;
    for (const tok of tokens) {
      const { score: s, at } = tokenScore(hay, tok);
      if (s < 0) {
        matched = false;
        break;
      }
      score += s;
      ranges.push([at, at + tok.length]);
    }
    if (!matched) continue;

    const row = index.rows[i];
    score += kindBonus(row);
    if (row.m === currentModule) score += CURRENT_MODULE_BONUS;

    hits.push({
      row,
      group: groupOf(row),
      score,
      href: hrefFor(row, index.mods),
      breadcrumb: breadcrumbFor(row, index),
      ranges: mergeRanges(ranges),
    });
  }

  hits.sort((a, b) => b.score - a.score || a.row.t.length - b.row.t.length);
  return hits.slice(0, limit);
}

function breadcrumbFor(row: IndexRow, index: PreparedIndex): string {
  const moduleTitle = index.mods[row.m]?.title ?? '';
  if (row.k === 'h' || row.k === 'c') {
    const doc = index.docTitles.get(`${row.m}/${row.s}`) ?? row.s ?? '';
    return `${moduleTitle} · ${withoutModulePrefix(doc, moduleTitle)}`;
  }
  return moduleTitle;
}

/**
 * Several modules title their theory files "<Module> — <Topic>", which would
 * make the breadcrumb read "Go · Go — Память, GC…" and then truncate away the
 * only informative half.
 */
function withoutModulePrefix(docTitle: string, moduleTitle: string): string {
  if (!moduleTitle || !normalize(docTitle).startsWith(normalize(moduleTitle))) {
    return docTitle;
  }
  const rest = docTitle.slice(moduleTitle.length).replace(/^[\s—–:·-]+/, '');
  return rest || docTitle;
}
