services:
  postgres-learn-app:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: interview_prep
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - learn_app_pg_data:/var/lib/postgresql/data

volumes:
  learn_app_pg_data:
